/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulacionesRouteImport } from './routes/simulaciones'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const SimulacionesRoute = SimulacionesRouteImport.update({
  id: '/simulaciones',
  path: '/simulaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/simulaciones': typeof SimulacionesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/simulaciones': typeof SimulacionesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/configuracion': typeof ConfiguracionRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRoute
  '/home': typeof HomeRoute
  '/simulaciones': typeof SimulacionesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/configuracion'
    | '/dashboard'
    | '/feed'
    | '/home'
    | '/simulaciones'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/configuracion'
    | '/dashboard'
    | '/feed'
    | '/home'
    | '/simulaciones'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/configuracion'
    | '/dashboard'
    | '/feed'
    | '/home'
    | '/simulaciones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRoute
  HomeRoute: typeof HomeRoute
  SimulacionesRoute: typeof SimulacionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulaciones': {
      id: '/simulaciones'
      path: '/simulaciones'
      fullPath: '/simulaciones'
      preLoaderRoute: typeof SimulacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRoute,
  HomeRoute: HomeRoute,
  SimulacionesRoute: SimulacionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
